/* This file is automatically generated with "make include/build_env.h". DO NOT EDIT */

#ifndef _BUILD_ENV_H
#define _BUILD_ENV_H

#define BUILD_ENV_UNAME "Linux ubuntu 2.6.38-10-server #46-Ubuntu SMP Tue Jun 28 16:31:00 UTC 2011 x86_64 x86_64 x86_64 GNU/Linux"
#define BUILD_ENV_DATE "Tue Jun 13 15:49:57 EDT 2017"
#define BUILD_ENV_SRCDIR "/home/anderson.deng/r7500-buildroot.git/build_dir/target-arm_v7-a_uClibc-0.9.33.2_eabi/samba/source"
#define BUILD_ENV_BUILDDIR "/home/anderson.deng/r7500-buildroot.git/build_dir/target-arm_v7-a_uClibc-0.9.33.2_eabi/samba/source"
#define BUILD_ENV_USER "anderson.deng"
#define BUILD_ENV_HOST "ubuntu"
#define BUILD_ENV_COMPILER "arm-openwrt-linux-uclibcgnueabi-gcc"
#endif /* _BUILD_ENV_H */
